[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/rachael.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  environment = { NETLIFY_EDGE_MIDDLEWARE = "v1" }
